# Generated by Django 5.1.4 on 2024-12-12 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=240)),
                ('lastName', models.CharField(max_length=240)),
                ('age', models.CharField(max_length=240)),
                ('mobile', models.CharField(max_length=12)),
                ('joined', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
