# Generated by Django 5.1.4 on 2024-12-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDA', '0004_alter_member_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_date',
            new_name='joinDate',
        ),
    ]
